#!/bin/bash
 
# Load resources
xrdb -merge .Xresources

# Set up an icon tray
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 10 --transparent true --tint 0x000000 --height 16 --alpha 0 &

# Cursor
#xsetroot -cursor_name left_ptr
 
# Set the background
[ -f "$HOME/.wallpaper" ] && (. $HOME/.wallpaper)
 
# Fire up apps
[ -x /usr/bin/xfsettingsd ]  && (xfsettingsd &)
[ -x /usr/bin/xscreensaver ] && (xscreensaver -no-splash &)
[ -x /usr/bin/redshift-gtk ] && (redshift-gtk &)
[ -x /usr/bin/nm-applet ]    && (nm-applet --sm-disable &)

# SSH and GPG agent
#eval $(gnome-keyring-daemon --start)
#export GNOME_KEYRING_CONTROL
#export SSH_AUTH_SOCK
#export GPG_AGENT_INFO
#export GNOME_KEYRING_PID

# Alternative
#eval $(gpg-agent --daemon)

# Fix Java applications
[ -x /usr/bin/wmname ] && (wmname LG3D)
 
# Start WM
exec xmonad
#dbus-launch --exit-with-session xmonad
